Repository sigpwny/websites, pull requests merged in 2023-05, with the labels that each got.

#43 Add events template page
  content/README.md
  content/events/uiuctf/2022/index.md
  gatsby-node.ts
  src/components/Card.tsx
  src/components/Card/card.css
  src/components/Card/index.tsx
  src/components/Card/placeholder.png
  src/components/CardGrid.tsx
  src/components/EventCards.tsx
  src/components/Icons.tsx
  src/global-types.d.ts
  src/pages/events.tsx
  src/pages_md/events.mdx
  src/pages_md/sponsors.mdx
  src/styles/main.css
  src/templates/template-event.tsx
  src/templates/template-meeting.tsx
Labels: enhancement

#38 Preliminary join page
  content/meetings/fa2022/2022-09-04/index.md
  content/meetings/fa2022/2022-09-08/index.md
  content/meetings/fa2022/2022-09-18/index.md
  content/meetings/fa2022/2022-09-22/index.md
  content/meetings/fa2022/2022-09-29/index.md
  gatsby-config.ts
  src/components/CardRow.tsx
  src/components/Footer.tsx
  src/components/Icons.tsx
  src/pages/index.tsx
  src/pages/join.tsx
  src/templates/template-meeting.tsx
  tailwind.config.js
Labels: content

#60 Improve Card components
  gatsby-node.ts
  src/components/Card/card.d.ts
  src/components/Card/index.tsx
  src/components/CardGrid.tsx
  src/components/CardRow.tsx
  src/global-types.d.ts
  src/pages/events.tsx
  src/pages/index.tsx
  src/pages/join.tsx
  src/pages/publications.tsx
Labels: feature
